### PR TITLE
feat(copy-link-to-clipboard): added feature to copy link to clipboard

### PR DESCRIPTION
**Pull request by abhishek-aa**
#75 added button and functionality to copy link to clipboard when web share api is not supported.

### CODE REVIEW

**Comment by abhishek-aa** [comment]
Please review and merge my pull request!

**Review by blenderskool — COMMENTED** [review]
@abhishek-aa Thanks for the PR! The changes look perfect and meets the expected behavior.

One minor addition I would like to suggest is to show a message in toast after a successful copy. The message shown can be "Room link copied to clipboard"

**Comment by abhishek-aa** [comment]
@blenderskool Sure!

**Comment by abhishek-aa** [comment]
Please review and merge my pull request!

**Comment by blenderskool** [comment]
Thank you for the PR @abhishek-aa :smile:

**Pull request merged**
