### PR TITLE
Changes for Issue #82

### PR DESCRIPTION
**Pull request by RotonEvan**
Added label in a tag and alt in img tag

### CODE REVIEW

**Review by blenderskool — APPROVED** [review]
Thanks for the changes @RotonEvan

**Comment by blenderskool** [comment]
@RotonEvan I changed the base branch to `next` as mentioned in CONTRIBUTING.md. There seems to be a merge conflict here

**Comment by RotonEvan** [comment]
@blenderskool it seems to be fine now. Can you check once?

**Review by RotonEvan — COMMENTED** [review]
I hope it's fine now

**Review by blenderskool — APPROVED** [review]
Perfect! Thanks again for the changes

Fixes #82

**Pull request merged**
